# Retail Sales Data Analysis — Pandas Project
## ***Project1***
* Name: Fares ali mohamed
* Student ID: 21148535
* Learning Path: Microsoft Data Engineer
* Instructor: Eng. Mohamed Hamed
* Classroom:ALX5_AIS5_S2

_____________

# Data Exploration & Cleaning

## Read the data from the data.csv file

In [2]:
import pandas as pd

In [3]:
with open('data.csv', 'r') as file:
    data = pd.read_csv(file)

In [4]:
display(data.head())
display(data.tail())
data.info()
data.describe()

,Retailer,Retailer ID,Invoice Date,Region,State,city,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method
0,Foot Locker,1185732,1/1/2020,Northeast,New York,New York,Men's Street Footwear,$50.00,"1,200","60,000","$30,000",In-store
1,Foot Locker,1185732,1/2/2020,Northeast,New York,New York,Men's Athletic Footwear,$50.00,"1,000","50,000","$15,000",In-store
2,Foot Locker,1185732,1/3/2020,Northeast,New York,New York,Women's Street Footwear,$40.00,"1,000","40,000","$14,000",In-store
3,Foot Locker,1185732,1/4/2020,Northeast,New York,New York,Women's Athletic Footwear,$45.00,850,"38,250","$13,388",In-store
4,Foot Locker,1185732,1/5/2020,Northeast,New York,New York,Men's Apparel,$60.00,900,"54,000","$16,200",In-store

,Retailer,Retailer ID,Invoice Date,Region,State,city,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method
9656,Foot Locker,1185732,1/24/2021,Northeast,New Hampshire,Manchester,Men's Apparel,$50.00,64,320,$90,Outlet
9657,Foot Locker,1185732,1/24/2021,Northeast,New Hampshire,Manchester,Women's Apparel,$41.00,105,431,$138,Outlet
9658,Foot Locker,1185732,2/22/2021,Northeast,New Hampshire,Manchester,Men's Street Footwear,$41.00,184,754,$279,Outlet
9659,Foot Locker,1185732,2/22/2021,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,$42.00,70,294,$123,Outlet
9660,Foot Locker,1185732,2/22/2021,Northeast,New Hampshire,Manchester,Women's Street Footwear,$29.00,83,241,$65,Outlet

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9661 entries, 0 to 9660
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Retailer          9661 non-null   object
 1   Retailer ID       9661 non-null   int64
 2   Invoice Date      9661 non-null   object
 3   Region            9654 non-null   object
 4   State             9661 non-null   object
 5   city              9661 non-null   object
 6   Product           9661 non-null   object
 7   Price per Unit    9659 non-null   object
 8   Units Sold        9661 non-null   object
 9   Total Sales       9661 non-null   object
 10  Operating Profit  9661 non-null   object
 11  Sales Method      9661 non-null   object
dtypes: int64(1), object(11)
memory usage: 905.8+ KB

        Retailer ID
count  9.661000e+03
mean   1.173864e+06
std    2.635259e+04
min    1.128299e+06
25%    1.185732e+06
50%    1.185732e+06
75%    1.185732e+06
max    1.197831e+06

________________________

## Explore the data

### Check for missing values

In [6]:
print(data.isnull().sum())

Retailer            0
Retailer ID         0
Invoice Date        0
Region              7
State               0
city                0
Product             0
Price per Unit      2
Units Sold          0
Total Sales         0
Operating Profit    0
Sales Method        0
dtype: int64

In [7]:
print(data.isnull().sum()/len(data) * 100)

Retailer            0.000000
Retailer ID         0.000000
Invoice Date        0.000000
Region              0.072456
State               0.000000
city                0.000000
Product             0.000000
Price per Unit      0.020702
Units Sold          0.000000
Total Sales         0.000000
Operating Profit    0.000000
Sales Method        0.000000
dtype: float64

### Check for duplicate records

In [8]:
print('Duplicate rows:', data.duplicated().sum())

Duplicate rows: 13

### Check the data types of all columns

In [9]:
print(data.dtypes)

Retailer            object
Retailer ID          int64
Invoice Date        object
Region              object
State               object
city                object
Product             object
Price per Unit      object
Units Sold          object
Total Sales         object
Operating Profit    object
Sales Method        object
dtype: object

## Convert columns to the appropriate data types where necessary:

### Convert `Invoice Date` to datetime

In [10]:
data['Invoice Date'] = pd.to_datetime(data['Invoice Date'])

In [11]:
data.dtypes

Retailer                    object
Retailer ID                  int64
Invoice Date        datetime64[ns]
Region                      object
State                       object
city                        object
Product                     object
Price per Unit              object
Units Sold                  object
Total Sales                 object
Operating Profit            object
Sales Method                object
dtype: object

### Convert numeric and currency columns to numeric values

In [12]:
display(data.head())
data.dtypes

,Retailer,Retailer ID,Invoice Date,Region,State,city,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,$50.00,"1,200","60,000","$30,000",In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,$50.00,"1,000","50,000","$15,000",In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,$40.00,"1,000","40,000","$14,000",In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,$45.00,850,"38,250","$13,388",In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,$60.00,900,"54,000","$16,200",In-store

Retailer                    object
Retailer ID                  int64
Invoice Date        datetime64[ns]
Region                      object
State                       object
city                        object
Product                     object
Price per Unit              object
Units Sold                  object
Total Sales                 object
Operating Profit            object
Sales Method                object
dtype: object

In [38]:
cols_to_numeric = ['Price per Unit', 'Units Sold', 'Total Sales', 'Operating Profit']
for col in cols_to_numeric:
    if data[col].dtype == 'object':
        data[col]=(
            data[col]
            .str.replace('$', '', regex=False)
            .str.replace(',', '', regex=False)
            .str.strip()

        )
    data[col] = pd.to_numeric(data[col], errors='coerce')
display(data.head())
data.dtypes

,Retailer,Retailer ID,Invoice Date,Region,State,city,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,60000,30000,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,50000,15000,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,40000,14000,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,38250,13388,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,54000,16200,In-store

Retailer                    object
Retailer ID                  int64
Invoice Date        datetime64[ns]
Region                      object
State                       object
city                        object
Product                     object
Price per Unit             float64
Units Sold                   int64
Total Sales                  int64
Operating Profit             int64
Sales Method                object
dtype: object

## Create new columns from `Invoice Date

In [16]:
data['day'] = data['Invoice Date'].dt.day
data['month'] = data['Invoice Date'].dt.month
data['year'] = data['Invoice Date'].dt.year
display(data[['Invoice Date', 'day', 'month', 'year']].head())

  Invoice Date  day  month  year
0   2020-01-01    1      1  2020
1   2020-01-02    2      1  2020
2   2020-01-03    3      1  2020
3   2020-01-04    4      1  2020
4   2020-01-05    5      1  2020

In [19]:
display(data.head())

,Retailer,Invoice Date,Region,State,city,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method,day,month,year
0,Foot Locker,2020-01-01,Northeast,New York,New York,Men's Street Footwear,$50.00,"1,200","60,000","$30,000",In-store,1,1,2020
1,Foot Locker,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,$50.00,"1,000","50,000","$15,000",In-store,2,1,2020
2,Foot Locker,2020-01-03,Northeast,New York,New York,Women's Street Footwear,$40.00,"1,000","40,000","$14,000",In-store,3,1,2020
3,Foot Locker,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,$45.00,850,"38,250","$13,388",In-store,4,1,2020
4,Foot Locker,2020-01-05,Northeast,New York,New York,Men's Apparel,$60.00,900,"54,000","$16,200",In-store,5,1,2020

## Drop unnecessary columns such as `Retailer ID

In [ ]:
# safely drop Retailer ID if it exists
data.drop(columns=['Retailer ID'], errors='ignore', inplace=True)
display(data.head())

KeyError: "['Retailer ID'] not found in axis"

In [45]:
display(data.columns)

Index(['Retailer', 'Invoice Date', 'Region', 'State', 'city', 'Product',
       'Price per Unit', 'Units Sold', 'Total Sales', 'Operating Profit',
       'Sales Method', 'day', 'month', 'year'],
      dtype='object')

## Handle missing values appropriately.

In [46]:
data['Region']= data['Region'].fillna('Unknown')

mean_price_per_unit = data['Price per Unit'].mean()
data['Price per Unit'] = data['Price per Unit'].fillna(mean_price_per_unit)

print(data.isnull().sum())

Retailer            0
Invoice Date        0
Region              0
State               0
city                0
Product             0
Price per Unit      0
Units Sold          0
Total Sales         0
Operating Profit    0
Sales Method        0
day                 0
month               0
year                0
dtype: int64

## Check the `Region` column and make sure there are no typos or inconsistent names.

In [47]:
print(data['Region'].unique())

['Northeast' 'South' 'Unknown' 'West' 'Midwest' 'Southeast']

# Business Analysis

## Sales Analysis

### 1. What is the total sales?

In [5]:
display(data.head())

,Retailer,Retailer ID,Invoice Date,Region,State,city,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method
0,Foot Locker,1185732,1/1/2020,Northeast,New York,New York,Men's Street Footwear,$50.00,"1,200","60,000","$30,000",In-store
1,Foot Locker,1185732,1/2/2020,Northeast,New York,New York,Men's Athletic Footwear,$50.00,"1,000","50,000","$15,000",In-store
2,Foot Locker,1185732,1/3/2020,Northeast,New York,New York,Women's Street Footwear,$40.00,"1,000","40,000","$14,000",In-store
3,Foot Locker,1185732,1/4/2020,Northeast,New York,New York,Women's Athletic Footwear,$45.00,850,"38,250","$13,388",In-store
4,Foot Locker,1185732,1/5/2020,Northeast,New York,New York,Men's Apparel,$60.00,900,"54,000","$16,200",In-store

### 2. What is the average sales for every region?

### 3. What is the average sales for every product?

### 4. What is the count of each product?

### 5. What is the top product by total sales?

### 6. What is the lowest-performing product by total sales?

## Time Analysis

### 7. How many products were sold each year?

### 8. How have total sales changed over the years?

### 9. How do sales vary month over month?

## Retailer Analysis

### 10. Which retailer has the highest total sales?

### 11. Which retailer has the highest operating profit?

## Product & Profit Analysis

### 12. What is the most profitable product?

### 13. What is the average price per unit for each product?

## Geographic Analysis

### 14. Which region has the highest total sales?

### 15. Which city contributes the most to total sales?